export const students = [
    {
      id: 1,
      name: "Aarav Sharma",
      email: "aarav.sharma@example.com",
      mobile: "9876543210",
      age: 20,
      grade: "A",
      address: "123 Main St, Delhi",
      enrollmentYear: 2021,
      major: "Computer Science",
      gpa: 3.8,
      isActive: true
    },
    {
      id: 2,
      name: "Aanya Gupta",
      email: "aanya.gupta@example.com",
      mobile: "9876543211",
      age: 19,
      grade: "B",
      address: "456 Park Ave, Mumbai",
      enrollmentYear: 2022,
      major: "Mathematics",
      gpa: 3.5,
      isActive: true
    },
    {
      id: 3,
      name: "Vihaan Patel",
      email: "vihaan.patel@example.com",
      mobile: "9876543212",
      age: 21,
      grade: "C",
      address: "789 Green Rd, Bangalore",
      enrollmentYear: 2020,
      major: "Physics",
      gpa: 2.9,
      isActive: false
    },
    {
      id: 4,
      name: "Isha Nair",
      email: "isha.nair@example.com",
      mobile: "9876543213",
      age: 22,
      grade: "D",
      address: "101 Pine St, Chennai",
      enrollmentYear: 2019,
      major: "History",
      gpa: 2.4,
      isActive: true
    },
    {
      id: 5,
      name: "Krishna Verma",
      email: "krishna.verma@example.com",
      mobile: "9876543214",
      age: 20,
      grade: "A",
      address: "202 Oak Dr, Kolkata",
      enrollmentYear: 2021,
      major: "Economics",
      gpa: 3.7,
      isActive: true
    },
    {
      id: 6,
      name: "Ananya Reddy",
      email: "ananya.reddy@example.com",
      mobile: "9876543215",
      age: 23,
      grade: "B",
      address: "303 Lake View, Hyderabad",
      enrollmentYear: 2018,
      major: "Biology",
      gpa: 3.2,
      isActive: true
    },
    {
      id: 7,
      name: "Arjun Deshmukh",
      email: "arjun.deshmukh@example.com",
      mobile: "9876543216",
      age: 18,
      grade: "C",
      address: "404 Hill St, Pune",
      enrollmentYear: 2023,
      major: "Literature",
      gpa: 2.8,
      isActive: true
    },
    {
      id: 8,
      name: "Sanya Mehta",
      email: "sanya.mehta@example.com",
      mobile: "9876543217",
      age: 21,
      grade: "D",
      address: "505 Elm St, Jaipur",
      enrollmentYear: 2020,
      major: "Political Science",
      gpa: 2.3,
      isActive: false
    },
    {
      id: 9,
      name: "Rohit Kumar",
      email: "rohit.kumar@example.com",
      mobile: "9876543218",
      age: 19,
      grade: "A",
      address: "606 Willow St, Chandigarh",
      enrollmentYear: 2022,
      major: "Chemistry",
      gpa: 3.9,
      isActive: true
    },
    {
      id: 10,
      name: "Diya Malhotra",
      email: "diya.malhotra@example.com",
      mobile: "9876543219",
      age: 22,
      grade: "B",
      address: "707 Cedar St, Surat",
      enrollmentYear: 2019,
      major: "Marketing",
      gpa: 3.6,
      isActive: true
    },
    {
      id: 11,
      name: "Manav Singh",
      email: "manav.singh@example.com",
      mobile: "9876543220",
      age: 23,
      grade: "C",
      address: "808 Walnut St, Lucknow",
      enrollmentYear: 2018,
      major: "Finance",
      gpa: 2.7,
      isActive: false
    },
    {
      id: 12,
      name: "Riya Das",
      email: "riya.das@example.com",
      mobile: "9876543221",
      age: 20,
      grade: "D",
      address: "909 Cherry Ln, Patna",
      enrollmentYear: 2021,
      major: "Sociology",
      gpa: 2.2,
      isActive: true
    },
    {
      id: 13,
      name: "Kabir Chawla",
      email: "kabir.chawla@example.com",
      mobile: "9876543222",
      age: 19,
      grade: "A",
      address: "1010 Birch St, Kanpur",
      enrollmentYear: 2022,
      major: "Engineering",
      gpa: 3.85,
      isActive: true
    },
    {
      id: 14,
      name: "Mira Pandey",
      email: "mira.pandey@example.com",
      mobile: "9876543223",
      age: 21,
      grade: "B",
      address: "1111 Maple Dr, Bhopal",
      enrollmentYear: 2020,
      major: "Psychology",
      gpa: 3.4,
      isActive: true
    },
    {
      id: 15,
      name: "Yash Thakur",
      email: "yash.thakur@example.com",
      mobile: "9876543224",
      age: 18,
      grade: "C",
      address: "1212 Aspen Way, Amritsar",
      enrollmentYear: 2023,
      major: "Philosophy",
      gpa: 2.6,
      isActive: true
    },
    {
      id: 16,
      name: "Aisha Agarwal",
      email: "aisha.agarwal@example.com",
      mobile: "9876543225",
      age: 20,
      grade: "D",
      address: "1313 Poplar Ave, Indore",
      enrollmentYear: 2021,
      major: "Music",
      gpa: 2.1,
      isActive: false
    },
    {
      id: 17,
      name: "Aryan Joshi",
      email: "aryan.joshi@example.com",
      mobile: "9876543226",
      age: 19,
      grade: "A",
      address: "1414 Cypress St, Nagpur",
      enrollmentYear: 2022,
      major: "Art",
      gpa: 3.95,
      isActive: true
    },
    {
      id: 18,
      name: "Tanvi Pillai",
      email: "tanvi.pillai@example.com",
      mobile: "9876543227",
      age: 23,
      grade: "B",
      address: "1515 Spruce St, Thane",
      enrollmentYear: 2018,
      major: "Law",
      gpa: 3.3,
      isActive: false
    },
    {
      id: 19,
      name: "Rishi Sinha",
      email: "rishi.sinha@example.com",
      mobile: "9876543228",
      age: 22,
      grade: "C",
      address: "1616 Dogwood Ln, Nashik",
      enrollmentYear: 2019,
      major: "Architecture",
      gpa: 2.75,
      isActive: true
    },
    {
      id: 20,
      name: "Nisha Kapoor",
      email: "nisha.kapoor@example.com",
      mobile: "9876543229",
      age: 21,
      grade: "D",
      address: "1717 Cedar St, Vijayawada",
      enrollmentYear: 2020,
      major: "Environmental Science",
      gpa: 2.3,
      isActive: true
    },
    {
      id: 21,
      name: "Aditya Saxena",
      email: "aditya.saxena@example.com",
      mobile: "9876543230",
      age: 20,
      grade: "A",
      address: "1818 Redwood St, Coimbatore",
      enrollmentYear: 2021,
      major: "Astronomy",
      gpa: 3.9,
      isActive: true
    },
    {
      id: 22,
      name: "Lavanya Bhatt",
      email: "lavanya.bhatt@example.com",
      mobile: "9876543231",
      age: 18,
      grade: "B",
      address: "1919 Fir St, Madurai",
      enrollmentYear: 2023,
      major: "Nursing",
      gpa: 3.5,
      isActive: true
    },
    {
      id: 23,
      name: "Kunal Ghosh",
      email: "kunal.ghosh@example.com",
      mobile: "9876543232",
      age: 21,
      grade: "C",
      address: "2020 Palm St, Vadodara",
      enrollmentYear: 2020,
      major: "Geology",
      gpa: 2.85,
      isActive: true
    },
    {
      id: 24,
      name: "Radhika Roy",
      email: "radhika.roy@example.com",
      mobile: "9876543233",
      age: 19,
      grade: "D",
      address: "2121 Magnolia Ave, raipur",
      enrollmentYear: 2022,
      major: "Journalism",
      gpa: 2.2,
      isActive: false
    },
    {
      id: 25,
      name: "Shaurya Bajaj",
      email: "shaurya.bajaj@example.com",
      mobile: "9876543234",
      age: 20,
      grade: "A",
      address: "2222 Laurel St, Faridabad",
      enrollmentYear: 2021,
      major: "Engineering",
      gpa: 3.75,
      isActive: true
    },
    {
      id: 26,
      name: "Meera Iyer",
      email: "meera.iyer@example.com",
      mobile: "9876543235",
      age: 22,
      grade: "B",
      address: "2323 Elm St, Ranchi",
      enrollmentYear: 2019,
      major: "Anthropology",
      gpa: 3.4,
      isActive: true
    },
    {
      id: 27,
      name: "Nikhil Malhotra",
      email: "nikhil.malhotra@example.com",
      mobile: "9876543236",
      age: 23,
      grade: "C",
      address: "2424 Birch Ln, Gwalior",
      enrollmentYear: 2018,
      major: "Physics",
      gpa: 2.8,
      isActive: false
    },
    {
      id: 28,
      name: "Pari Rao",
      email: "pari.rao@example.com",
      mobile: "9876543237",
      age: 21,
      grade: "D",
      address: "2525 Oak Dr, Mysore",
      enrollmentYear: 2020,
      major: "Art History",
      gpa: 2.1,
      isActive: true
    },
    {
      id: 29,
      name: "Dev Arora",
      email: "dev.arora@example.com",
      mobile: "9876543238",
      age: 20,
      grade: "A",
      address: "2626 Maple Ave, Jodhpur",
      enrollmentYear: 2021,
      major: "Statistics",
      gpa: 3.85,
      isActive: true
    },
    {
      id: 30,
      name: "Sara Khan",
      email: "sara.khan@example.com",
      mobile: "9876543239",
      age: 19,
      grade: "B",
      address: "2727 Pine St, Raipur",
      enrollmentYear: 2022,
      major: "Microbiology",
      gpa: 3.6,
      isActive: true
    },
    {
      id: 31,
      name: "Arnav Dubey",
      email: "arnav.dubey@example.com",
      mobile: "9876543240",
      age: 22,
      grade: "C",
      address: "2828 Spruce Ln, Aurangabad",
      enrollmentYear: 2019,
      major: "Computer Science",
      gpa: 2.7,
      isActive: false
    },
    {
      id: 32,
      name: "Neha Chatterjee",
      email: "neha.chatterjee@example.com",
      mobile: "9876543241",
      age: 23,
      grade: "D",
      address: "2929 Redwood Rd, Maharashtra",
      enrollmentYear: 2018,
      major: "Sociology",
      gpa: 2.3,
      isActive: true
    },
    {
      id: 33,
      name: "Avi Saxena",
      email: "avi.saxena@example.com",
      mobile: "9876543242",
      age: 21,
      grade: "A",
      address: "3030 Cedar Rd, Ghaziabad",
      enrollmentYear: 2020,
      major: "Engineering",
      gpa: 3.9,
      isActive: true
    },
    {
      id: 34,
      name: "Pia Mukherjee",
      email: "pia.mukherjee@example.com",
      mobile: "9876543243",
      age: 18,
      grade: "B",
      address: "3131 Elm St, Kota",
      enrollmentYear: 2023,
      major: "Chemistry",
      gpa: 3.45,
      isActive: true
    },
    {
      id: 35,
      name: "Rohan Desai",
      email: "rohan.desai@example.com",
      mobile: "9876543244",
      age: 19,
      grade: "C",
      address: "3232 Oak St, Jabalpur",
      enrollmentYear: 2022,
      major: "Psychology",
      gpa: 2.8,
      isActive: false
    },
    {
      id: 36,
      name: "Vani Sharma",
      email: "vani.sharma@example.com",
      mobile: "9876543245",
      age: 20,
      grade: "D",
      address: "3333 Palm St, Meerut",
      enrollmentYear: 2021,
      major: "History",
      gpa: 2.1,
      isActive: true
    },
    {
      id: 37,
      name: "Arya Ghosh",
      email: "arya.ghosh@example.com",
      mobile: "9876543246",
      age: 22,
      grade: "A",
      address: "3434 Spruce Ln, Varanasi",
      enrollmentYear: 2019,
      major: "Political Science",
      gpa: 3.8,
      isActive: true
    },
    {
      id: 38,
      name: "Ishaan Verma",
      email: "ishaan.verma@example.com",
      mobile: "9876543247",
      age: 21,
      grade: "B",
      address: "3535 Birch Rd, Guwahati",
      enrollmentYear: 2020,
      major: "Geography",
      gpa: 3.3,
      isActive: false
    },
    {
      id: 39,
      name: "Kriti Chopra",
      email: "kriti.chopra@example.com",
      mobile: "9876543248",
      age: 19,
      grade: "C",
      address: "3636 Maple Ln, Bhubaneswar",
      enrollmentYear: 2022,
      major: "Economics",
      gpa: 2.7,
      isActive: true
    },
    {
      id: 40,
      name: "Raghav Jain",
      email: "raghav.jain@example.com",
      mobile: "9876543249",
      age: 20,
      grade: "D",
      address: "3737 Poplar Ave, Udaipur",
      enrollmentYear: 2021,
      major: "Philosophy",
      gpa: 2.4,
      isActive: false
    }
  ];